name: Docker build and push to ghcr

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  docker-build-push:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          ## TODO You need your own ghcr user
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Tag Bump
        id: bump_version
        uses: anothrNick/github-tag-action@18284c78f6ac68868d5341f57c4f971fb5b7605c # 1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true

      - run: echo "tag=ghcr.io/oslokommune/okctl-kotlin-app-template" >> $GITHUB_ENV
        id: tag_store
      - run: echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        id: version_store

      - name: Build and push Docker images
        run: docker build -t ${{ env.tag }}:${{ env.version }} .

      - name: Push docker image
        run: docker push ${{ env.tag }}:${{ env.version }}
