name: Temp debug action

on:
  workflow_dispatch:
  push:
    branches:
      - 'gitref'

jobs:
  update-tag:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - uses: actions/checkout@v2
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'oslokommune/okctl-demo-iac'
          ref: 'main'
          ssh-key: '${{ secrets.CLUSTER_DEPLOY_KEY_DEMO }}'



      - run: echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        id: version_store

      - name: Update IAC repo with image
        env:
          CONTAINER_NAME: ghcr.io/oslokommune/okctl-kotlin-app-template
          IMAGE_TAG: ${ version }
          DEPLOYMENT_YAML_FILE: infrastructure/applications/demo-app/overlays/okctl-demo-dev/deployment-patch.json
        run: |
          echo "Beofre tag"
          echo $IMAGE_TAG
          echo "After tag"
